version: '3.8'

services:
  #php customi
  app-laravel:
    build:
      args:
        user: brunin
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: brunoholanda95/laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - docker-laravel

  #server nginx
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 83:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - docker-laravel

  #redis cache
  redis:
    image: redis:latest
    networks:
      - docker-laravel
  
  #database mysql
  mysql:
    image: mysql:5.7.22
    restart: always
    ports: 
      - 3307:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./.docker/mysql:/var/lib/mysql

networks:
  docker-laravel:
    driver: bridge